### PR TITLE
add main

### PR DESCRIPTION
**Pull request by manuandru**

### CODE REVIEW

**Comment by kelvin-olaiya** [comment]
First of all, there's no description! 
You're a github villain!

**Comment by kelvin-olaiya** [comment]
Anyway, i'll dive into it...

**Review by kelvin-olaiya — COMMENTED** [review]
Is this a change I can take from the truth repo or just internal?

**Comment by manuandru** [comment]
I think this is a vital part of the repo, if you don't merge as is I will never work more for free

**Review by kelvin-olaiya — APPROVED** [review]

**Pull request merged**
